:toc:

== Plan

// tag::workout-plan[]
[cols="1,1,1,1,1,1,1,1,1,1,1,1,1",options="header"]
|===
3+|Monday                                             |Tuesday 3+|Wednesday                                                     |Thursday 3+|Friday                                                   |Saturday    |Sunday
  |Exercise                            |Sets |Reps .9+|Rest Day  |Exercise                                       |Sets |Reps .9+|Rest Day   |Exercise                                  |Sets |Reps .9+|Rest Day .9+|Rest Day
  |Squat (Barbell)                     |3    |6                  |Deadlift (Barbell)                             |3    |5                   |Walking Lunge (Dumbbell)                  |3    |20
  |Bench Press (Barbell)               |3    |8                  |Overhead Press (Barbell)                       |3    |8                   |Incline Bench Press (Barbell)             |3    |8
  |Overhand Grip Pull Up               |3    |8                  |Incline Chest-Supported Elbows-In Dumbbell Row |3    |12                  |Cross-Body Cable Lat Pull-Around          |3    |10
  |Dip                                 |3    |8                  |Leg Extension                                  |3    |12                  |Sideways Single Arm Machine Rear Delt Fly |3    |12
  |Standing Calf Raise                 |4    |10                 |Chest Fly (Machine)                            |3    |12                  |Seated Leg Curl                           |3    |10
  |Single Arm High Cable Lateral Raise |4    |10                 |Hanging Knee Raise                             |3    |12                  |Single Arm High Cable Lateral Raise       |4    |10
  |Cable Crunch                        |3    |12                 |Overhead Triceps Extension (Cable)             |3    |12                  |Standing Calf Raise                       |4    |10
  |Single Arm Preacher Curl (Dumbbell) |3    |10                 |                                               |     |                    |Single Arm Bayesian Curl (Cable)          |3    |10
|===
// end::workout-plan[]

=== Progression System

* For exercises with 3 sets:
.. Pick a weight
.. For set 1, target the number of sets in the plan
.. For set 2:
*** if set 1 was successful, target the numer of sets in the plan
*** if set 1 was unsuccessful, decrease the weight and target the number of sets in the plan
.. For set 3:
*** if set 2 was successful, go to failure
*** if set 2 was unsuccessful, decrease the weight and go to failure
.. Set 3 is considered successful if I did at least the number of reps in the plan (sometimes n-1 or even n-2 - at my discretion) with the weight from set 1
.. Choose weight for the next week
*** if set 3 was successful, increase the weight for the next week
*** if set 3 was unsuccessful, start with the same weight for the next week

* For Squat, Bench Press and Incline Bench Press the last set shouldn't be taken to failure, but it should be aimed to be as close to failure as possible (min 8 RPE), while avoiding killing myself

* For exercises with 4 sets:
.. I still have to come up with a system
.. TBD

=== Exercise Selection

I started with buying Fundamentals Hypertrophy Program from Jeff Nippard, available link:Fundamentals_Hypertrophy_Program.pdf[here]. After a lot of training using the FBW workouts from the program, I decided to make some adjustments based on:

* My goals - there is a lot of legs volume that I much prefer to allocate elsewhere, but I still don't want to neglect them. In fact I added calves volume
* Compound movements - I want to focus on them, because they stimulate more muscle groups, they are great for hypertrophy, and they give me a lot of satisfaction
* Science - over the years the science got updated and it turns out tension in the stretched position is more important for hypertrophy than in the contracted position [source needed], so I replaced some exercises with this in mind, for example:
** Lying Leg Curl -> Seated Leg Curl (if you lean forward, your Hamstrings get more stretch)
** Supinated Dumbbell Curl -> Preacher Curl, Bayesian Curl
** Lateral Raise (Dumbbell) -> High Cable Lateral Raise
* My preferences - some of them I just _want_ to do, for example:
** Incline Bench Press (Dumbbell) -> Incline Bench Press (Barbell)
** Lat Pulldown -> Overhead Grip Pull Up

Exercises are subject to change based on new scientific discoveries and my preferences.

=== Exercise Order

Exercise order is based on the following principles:

* I want to do the most important, compound movements first because
** They require the most energy and focus, so I want to do them when I'm fresh
** They stimulate the most muscle groups, so when I don't have much time, I can do them and leave the gym while still getting a good FBW workout
** I respect them the most and they have a potential competitive factor to them, so I want to get as strong as possible at them

* Isolation movements are separated in a way that allows muscles to recover as much as possible between exercises
** This order has beed adjusted based on how I felt during the workout
** For example, I moved Standing Calf Raise to before Single Arm High Cable Lateral Raise on Monday, because I realised that even though Dips don't use Side Delts as much, my entire arms where fatigued after all the compound movements

* Muscle groups are split into two/three days as evenly as possible because doing less sets per muscle group per session but more sessions per week is better for hypertrophy than doing them all in one day, even if the total number of sets per week is the same [source needed]

=== Things to consider

* Decreasing volume while increasing intensity may be beneficial [source needed]

=== Working Sets Per Muscle Group Count Summary

[cols="1,1,1,1,1,1,1,1",options="header"]
|===
   |Muscle Group |Monday |Wednesday |Friday |Sum  |Goal |Goal - Sum Diff |OK?
8+^|Upper Body
   |Chest        |6      |3         |3      |12   |12   |0               |✅
   |Abs          |3      |3         |0      |6    |6    |0               |✅
8+^|Back
   |Lats         |3      |3         |3      |9    |12   |3               |✅
   |Upper Back   |1.5    |6         |3      |10.5 |6    |-4.5            |✅
   |Lower Back   |1.5    |1.5       |0      |3    |6    |3               |✅
8+^|Arms
   |Biceps       |6      |1.5       |6      |13.5 |12   |-1.5            |✅
   |Triceps      |3      |4.5       |1.5    |9    |12   |3               |✅
   |Forearms     |1.5    |3         |3      |7.5  |9    |1.5             |✅
8+^|Shoulders
   |Front Delts  |5      |4.5       |5      |14.5 |12   |-2.5            |✅
   |Side Delts   |4      |1.5       |4      |9.5  |12   |2.5             |✅
   |Rear Delts   |1.5    |3         |4.5    |9    |12   |3               |✅
8+^|Legs
   |Quads        |3      |4.5       |3      |10.5 |12   |1.5             |✅
   |Calves       |4      |0         |5.5    |9.5  |9    |-0.5            |✅
   |Glutes       |3      |3         |3      |9    |6    |-3              |✅
   |Hamstrings   |3      |0         |3      |6    |6    |0               |✅
8+^|No priority
   |Serratus     |0      |1.5       |0      |1.5  |0    |-1.5            |✅
   |Obliques     |1.5    |1.5       |0      |3    |0    |-3              |✅
   |Traps        |2      |3         |3.5    |8.5  |0    |-8.5            |✅
   |Neck         |0      |0         |0      |0    |0    |0               |✅
   |Adductors    |3      |3         |3      |9    |0    |-9              |✅
|===

==== How are these numbers calculated?

Each exercise is assigned to a primary muscle group and a secondary muscle group. The information is taken from the MacroFactor app. For each set of given exercise, one set is added to primary muscle groups assigned to that exercise, and half a set is added to secondary muscle groups.

== Weekly Working Sets Goal

[cols="1,1,1,1,1,1,1,1,1,1",options="header"]
|===
2+^|Upper body    2+^|Back        2+^|Arms      2+^|Shoulders    2+^|Legs
   |Chest    |12     |Lats       |12 |Biceps   |12 |Front Delts |12 |Quads      |12
   |Abs      |6      |Upper Back |6  |Triceps  |12 |Side Delts  |12 |Calves     |9
   |Obliques |0      |Lower Back |6  |Forearms |9  |Rear Delts  |12 |Glutes     |6
   |Serratus |0      |Traps      |0  |         |   |            |   |Hamstrings |6
   |Neck     |0      |           |   |         |   |            |   |Adductors  |0
|===

=== How have I come up with these numbers?
* I am still a beginner
* I want to train 3 times a week
* Training a muscle group more than once a week is optimal for hypertrophy [source needed]
* 6 sets per week divided into two sessions per muscle group should be enough for me to make gains [source needed], so until I'm more advanced, I don't want to exceed 12 sets for muscle groups that I care most about

=== How to read this table?
* The left part of each row is a muscle group, and the right is the number of sets I want to do for that muscle group per week.
* 12 - high priority muscle group. 12 is the perfect target, but I'm fine with 10+. If I exceed 12, I'm probably spending more time in the gym than I want to
* 9 - medium priority muscle group. I still want to make sure that those muscle groups get a lot of stimulus, either secondary from compounds movements (e.g. forearms) or direct isolation work (e.g. calves), but these are where I'm starting to save time spent in the gym. 7.5+ sets total per week is good enough as long as I hit them at least twice a week
* 6 - low priority muscle group. We're starting to get into the territory of not caring about the muscle groups as much, but the numbers will be based on my personal preference. For example:
** Glutes - I won't be targeting them other than doing exercises that target them naturally, because I think my glutes are naturally big
** Hamstrings - I don't like to train them, but I know it's important so I will target them once a week for 3 sets and get the rest of the stimulus from compound movements
** Abs - I care about them a lot, and I want them to look good when I lose fat, they don't get stimulated enough from compound movements, so I will target them directly twice a week for 3 sets each time, but they're not higher in priorities because I simply don't think they need more than 6 sets per week
* 0 - no priority muscle group. I don't care about them at all, but there will be differences based on my preference. For example:
** Traps - they will be getting some stimulus from other movements and I think it's fine
** Neck - I want to avoid training it at all, because I know I have a tendency to get sleep apnea, and I don't want to make it worse by making my neck bigger
